// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreAPI.Models;

namespace StoreAPI.Migrations
{
    [DbContext(typeof(StoreDetailContext))]
    partial class StoreDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StoreAPI.Models.StoreDetail", b =>
                {
                    b.Property<int>("StoreDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("StoreAddress")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StoreItems")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StoreName")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StoreWorkTime")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("StoreDetailId");

                    b.ToTable("StoreDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
